### ISSUE TITLE
JDR Report generation fails for Containerized EAP server

### ISSUE THREAD

**Issue by hhovsepy** [ManageIQ/manageiq-providers-hawkular#52]
Generating JDR Reports fails for EAP servers which are started in Docker Container.
In Summary Page, button is available, but all executions on the end failed with Error.

Warn is logged on container side:
10:49:54,850 WARN  [org.hawkular.agent.monitor.cmd.GenericErrorResponseCommand] (OkHttp http://last-hawkular-services.bc.jonqe.lab.eng.bos.redhat.com:8080/...) HAWKMONITOR010043: Received the following error message and stack trace from server: Failed to process message [org.hawkular.cmdgw.api.GenericErrorResponse]
org.hawkular.cmdgw.NoCommandForMessageException: No command found for requestClass [org.hawkular.cmdgw.api.GenericErrorResponse]
	at org.hawkular.cmdgw.command.ws.WsCommands.getCommands(WsCommands.java:79)
	at org.hawkular.cmdgw.command.ws.WsCommands$Proxy$_$$_WeldClientProxy.getCommands(Unknown Source)
	at org.hawkular.cmdgw.command.ws.server.AbstractGatewayWebSocket.handleRequest(AbstractGatewayWebSocket.java:98)
	at org.hawkular.cmdgw.command.ws.server.AbstractGatewayWebSocket.onMessage(AbstractGatewayWebSocket.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87)
	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$2$1.run(AnnotatedEndpoint.java:150)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:553)
	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$2.onMessage(AnnotatedEndpoint.java:145)
	at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:283)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:553)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$5.run(ServerWebSocketContainer.java:538)
	at io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

![screenshot from 2017-09-19 12 50 05](https://user-images.githubusercontent.com/604313/30589220-dcb266ea-9d39-11e7-9bde-c111e33753e4.png)

**Comment by abonas** [comment]
@israel-hdez the JDR should be either greyed out or not displayed at all for containerized, similar to power operations.
@hhovsepy good catch :+1:

**Comment by israel-hdez** [comment]
@hhovsepy do you know if the agent on the EAP is based on, at least, upstream 1.0.0.CR6? I am able to generate it using https://hub.docker.com/r/hawkular/wildfly-hawkular-javaagent/ "latest" tag.

**Comment by hhovsepy** [comment]
@israel-hdez the problem was in tested image, even it was the latest, but was using CR5.
Closing the issue.

**Comment by israel-hdez** [comment]
@hhovsepy Push the close button? :)

**Comment by hhovsepy** [comment]
:))
